### ISSUE TITLE
read error for Epever Triron 4210N

### ISSUE THREAD

**Issue by jimlynnjulian** [plopp/python-modbus-epever-xtra#2]
Hello,
   Thanks for the script.
I ran into what appears to be two simple errors.
1. The boost duration and equalization duration seem interchanged.
2. The duration is off by a decimal point.

actual values
BoostDur: 180 minutes
EqualDur: 0 minutes

read as
BoostDur: 0
EqualDur: 1.8min

Thanks again.

**Comment by plopp** [comment]
Hi! Thank you for your feedback. Would you mind creating a PR to fix this?

**Comment by jimlynnjulian** [comment]
Hello.
I'd like to, but I program only in conjunction with the design and maintenance of ongoing projects. I'm the kind of programmer who can write simple programs in several languages but nothing extensive in any one language. That and I'm currently very busy. Besides, I don't even know what a PR is. I also am not knowledgeable in Modbus.

Good luck.

**Comment by jimlynnjulian** [comment]
Hello,
My errors.
I added four lines to read and print durations for boost and equalization.

final:

EQUALIZATION_DURATION = 0x906B

BOOST_DURATION = 0x906C

boost_duration = instrument.read_register(BOOST_DURATION), 0)

equalization_duration = instrument.read_register(EQUALIZATION_DURATION), 2)

Thanks again.
